version: '3.1'
services:
    app:
        image: node:13.7.0-alpine3.11
        command: sh -c "npm i && npm run dev"
        working_dir: /srv
        volumes:
            - .:/srv
            - /srv/node_modules
        ports:
            - '3000:3000'
        environment:
            PORT: 3000
            MYSQL_HOST: database
            MYSQL_DATABASE: dev
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            SESSION_SECRET_KEY: secret
            REDIS_HOST: redis
        depends_on:
            - database
            - redis

    database:
        image: mysql:5.7.13
        environment:
            MYSQL_DATABASE: dev
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_RANDOM_ROOT_PASSWORD: 1

    redis:
        image: redis:5.0.7-alpine
